version: '3.1'

services:
  site1:
    image: cheops:latest
    volumes:
    - ./site/resources1.json:/app/resources.json:ro
    - ./sites.yaml:/app/sites.yaml:ro
    networks:
    - bridge
    environment:
    - SITE_ID=site1
    ports:
    - 5001:5000
  site2:
    image: cheops:latest
    volumes:
    - ./site/resources2.json:/app/resources.json:ro
    - ./sites.yaml:/app/sites.yaml:ro
    networks:
    - bridge
    environment:
    - SITE_ID=site2
    ports:
    - 5002:5000
  site3:
    image: cheops:latest
    volumes:
    - ./site/resources3.json:/app/resources.json:ro
    - ./sites.yaml:/app/sites.yaml:ro
    networks:
    - bridge
    environment:
    - SITE_ID=site3
    ports:
    - 5003:5000

networks:
  bridge:
    driver: bridge
