version: '3.1'

services:
  site1:
    image: site-worker:latest
    volumes:
    - ./resources1.json:/app/resources.json:ro
    networks:
    - bridge
    environment:
    - SITE_ID=site1
    ports:
    - 5001:5000
  site2:
    image: site-worker:latest
    volumes:
    - ./resources2.json:/app/resources.json:ro
    networks:
    - bridge
    environment:
    - SITE_ID=site2
    ports:
    - 5002:5000
  site3:
    image: site-worker:latest
    volumes:
    - ./resources3.json:/app/resources.json:ro
    networks:
    - bridge
    environment:
    - SITE_ID=site3
    ports:
    - 5003:5000

networks:
  bridge:
    driver: bridge
